services:
  ul-online:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - TRAFIKLAB_SWEDEN3_RT_KEY=${TRAFIKLAB_SWEDEN3_RT_KEY}
      - TRAFIKLAB_SWEDEN3_STATIC_KEY=${TRAFIKLAB_SWEDEN3_STATIC_KEY}
      - TRAFIKVERKET_OPEN_DATA_API_KEY=${TRAFIKVERKET_OPEN_DATA_API_KEY}
    volumes:
      - gtfs-data:/app/data
    restart: unless-stopped

volumes:
  gtfs-data: